package org.tctalent.anonymization.domain.common;


public enum HowHeardAboutUs {
  ONLINE_GOOGLE_SEARCH,
  FACEBOOK,
  INSTAGRAM,
  LINKEDIN,
  X,
  WHATSAPP,
  YOUTUBE,
  FRIEND_COLLEAGUE_REFERRAL,
  UNIVERSITY_SCHOOL_REFERRAL,
  EMPLOYER_REFERRAL,
  EVENT_WEBINAR,
  INFORMATION_SESSION,
  COMMUNITY_CENTRE_POSTING_FLYERS,
  OUTREACH_WORKER,
  NGO,
  UNHCR,
  OTHER
}