INSERT INTO public.country (id, iso_code, name, status) VALUES (0, NULL, 'Unknown', 'inactive');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6180, 'AF', 'Afghanistan', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6181, 'AL', 'Albania', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6182, 'DZ', 'Algeria', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6183, 'AS', 'American Samoa', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6184, 'AD', 'Andorra', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6185, 'AO', 'Angola', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6186, 'AI', 'Anguilla', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6188, 'AR', 'Argentina', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6189, 'AM', 'Armenia', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6190, 'AW', 'Aruba', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6191, 'AU', 'Australia', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6192, 'AT', 'Austria', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6193, 'AZ', 'Azerbaijan', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6194, 'BS', 'Bahamas', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6195, 'BH', 'Bahrain', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6196, 'BD', 'Bangladesh', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6197, 'BB', 'Barbados', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6198, 'BY', 'Belarus', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6199, 'BE', 'Belgium', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6200, 'BZ', 'Belize', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6201, 'BJ', 'Benin', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6202, 'BM', 'Bermuda', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6203, 'BT', 'Bhutan', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6204, 'BO', 'Bolivia', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6206, 'BW', 'Botswana', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6207, 'BR', 'Brazil', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6210, 'BN', 'Brunei', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6211, 'BG', 'Bulgaria', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6212, 'BF', 'Burkina Faso', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6214, 'KH', 'Cambodia', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6215, 'CM', 'Cameroon', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6216, 'CA', 'Canada', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6217, 'CV', 'Cape Verde', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6220, 'CF', 'Central African Republic', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6221, 'TD', 'Chad', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6222, 'CL', 'Chile', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6223, 'CN', 'China', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6226, 'CO', 'Colombia', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6230, 'CK', 'Cook Islands', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6231, 'CR', 'Costa Rica', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6233, 'HR', 'Croatia', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6234, 'CU', 'Cuba', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6236, 'CY', 'Cyprus', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6237, 'CZ', 'Czechia', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6239, 'DJ', 'Djibouti', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6240, 'DM', 'Dominica', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6241, 'DO', 'Dominican Republic', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6242, 'EC', 'Ecuador', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6243, 'EG', 'Egypt', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6245, 'GQ', 'Equatorial Guinea', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6246, 'ER', 'Eritrea', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6247, 'EE', 'Estonia', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6248, 'ET', 'Ethiopia', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6249, 'FK', 'Falkland Islands', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6250, 'FO', 'Faroe Islands', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6251, 'FJ', 'Fiji', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6253, 'FR', 'France', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6254, 'GF', 'French Guiana', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6255, 'PF', 'French Polynesia', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6256, 'GA', 'Gabon', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6257, 'GM', 'Gambia', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6259, 'DE', 'Germany', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6260, 'GH', 'Ghana', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6262, 'GR', 'Greece', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6263, 'GL', 'Greenland', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6264, 'GD', 'Grenada', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6265, 'GP', 'Guadeloupe', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6266, 'GU', 'Guam', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6269, 'GN', 'Guinea', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6270, 'GW', 'Guinea-Bissau', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6271, 'GY', 'Guyana', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6272, 'HT', 'Haiti', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6273, 'HN', 'Honduras', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6275, 'HU', 'Hungary', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6277, 'IN', 'India', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6278, 'ID', 'Indonesia', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6279, 'IR', 'Iran', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6280, 'IQ', 'Iraq', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6281, 'IE', 'Ireland', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6284, 'IT', 'Italy', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6285, 'JM', 'Jamaica', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6286, 'JP', 'Japan', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6289, 'KZ', 'Kazakhstan', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6290, 'KE', 'Kenya', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6291, 'KI', 'Kiribati', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6292, 'KW', 'Kuwait', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6293, 'KG', 'Kyrgyzstan', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6295, 'LV', 'Latvia', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6297, 'LS', 'Lesotho', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6298, 'LR', 'Liberia', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6299, 'LY', 'Libya', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6300, 'LI', 'Liechtenstein', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6301, 'LT', 'Lithuania', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6302, 'LU', 'Luxembourg', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6305, 'MG', 'Madagascar', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6307, 'MY', 'Malaysia', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6308, 'MV', 'Maldives', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6309, 'ML', 'Mali', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6310, 'MT', 'Malta', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6311, 'MH', 'Marshall Islands', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6312, 'MQ', 'Martinique', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6314, 'MU', 'Mauritius', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6316, 'MX', 'Mexico', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6319, 'MC', 'Monaco', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6320, 'MN', 'Mongolia', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6321, 'ME', 'Montenegro', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6322, 'MS', 'Montserrat', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6323, 'MA', 'Morocco', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6326, 'NA', 'Namibia', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6327, 'NR', 'Nauru', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6328, 'NP', 'Nepal', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6329, 'NL', 'Netherlands', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6330, 'NC', 'New Caledonia', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6331, 'NZ', 'New Zealand', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6332, 'NI', 'Nicaragua', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6334, 'NG', 'Nigeria', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6335, 'NU', 'Niue', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6337, 'KP', 'North Korea', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6339, 'NO', 'Norway', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6340, 'OM', 'Oman', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6341, 'PK', 'Pakistan', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6342, 'PW', 'Palau', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6344, 'PA', 'Panama', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6345, 'PG', 'Papua New Guinea', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6179, 'GB', 'United Kingdom', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (9430, NULL, 'Urdu', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6370, 'SC', 'Seychelles', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6371, 'SL', 'Sierra Leone', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (1000, NULL, 'Stateless', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6372, 'SG', 'Singapore', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6375, 'SI', 'Slovenia', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6376, 'SB', 'Solomon Islands', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6377, 'SO', 'Somalia', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6378, 'ZA', 'South Africa', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6410, 'UY', 'Uruguay', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6411, 'UZ', 'Uzbekistan', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6412, 'VU', 'Vanuatu', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6379, 'KR', 'South Korea', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6413, 'VA', 'Vatican City', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6187, 'AG', 'Antigua & Barbuda', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6205, 'BA', 'Bosnia & Herzegovina', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6213, 'BI', 'Burundi', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6227, 'KM', 'Comoros', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (1002, 'CG', 'Congo - Brazzaville', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (1001, 'CI', 'Côte d’Ivoire', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6238, 'DK', 'Denmark', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6244, 'SV', 'El Salvador', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6252, 'FI', 'Finland', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6258, 'GE', 'Georgia', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6267, 'GT', 'Guatemala', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6274, 'HK', 'Hong Kong SAR China', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6276, 'IS', 'Iceland', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6283, 'IL', 'Israel', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6288, 'JO', 'Jordan', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6296, 'LB', 'Lebanon', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6306, 'MW', 'Malawi', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6313, 'MR', 'Mauritania', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6324, 'MZ', 'Mozambique', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (9565, 'MM', 'Myanmar (Burma)', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6338, 'MP', 'Northern Mariana Islands', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6343, 'PS', 'Palestinian Territories', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6346, 'PY', 'Paraguay', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6347, 'PE', 'Peru', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6348, 'PH', 'Philippines', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6349, 'PL', 'Poland', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6350, 'PT', 'Portugal', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6351, 'PR', 'Puerto Rico', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6352, 'QA', 'Qatar', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6354, 'RO', 'Romania', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6355, 'RU', 'Russia', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6356, 'RW', 'Rwanda', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6364, 'WS', 'Samoa', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6365, 'SM', 'San Marino', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6366, 'ST', 'São Tomé & Príncipe', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6367, 'SA', 'Saudi Arabia', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6368, 'SN', 'Senegal', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6369, 'RS', 'Serbia', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6380, 'SS', 'South Sudan', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6381, 'ES', 'Spain', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6382, 'LK', 'Sri Lanka', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6359, 'KN', 'St. Kitts & Nevis', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6360, 'LC', 'St. Lucia', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6363, 'VC', 'St. Vincent & Grenadines', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6383, 'SD', 'Sudan', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6384, 'SR', 'Suriname', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6386, 'SZ', 'Swaziland', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6387, 'SE', 'Sweden', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6388, 'CH', 'Switzerland', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6389, 'SY', 'Syria', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6390, 'TW', 'Taiwan', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6391, 'TJ', 'Tajikistan', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6392, 'TZ', 'Tanzania', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6393, 'TH', 'Thailand', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6395, 'TG', 'Togo', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6397, 'TO', 'Tonga', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6398, 'TT', 'Trinidad & Tobago', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6399, 'TN', 'Tunisia', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6401, 'TM', 'Turkmenistan', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6403, 'TV', 'Tuvalu', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6405, 'UG', 'Uganda', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6406, 'UA', 'Ukraine', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6407, 'AE', 'United Arab Emirates', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6178, 'US', 'United States', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6414, 'VE', 'Venezuela', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6415, 'VN', 'Vietnam', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6417, 'EH', 'Western Sahara', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6418, 'YE', 'Yemen', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6419, 'ZM', 'Zambia', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6420, 'ZW', 'Zimbabwe', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (10000, 'CI', 'Côte d’Ivoire', 'inactive');
INSERT INTO public.country (id, iso_code, name, status) VALUES (10001, 'CD', 'Congo - Kinshasa', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (6400, 'TR', 'Türkiye', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (10002, 'LA', 'Laos', 'active');
INSERT INTO public.country (id, iso_code, name, status) VALUES (10003, 'KY', 'Cayman Islands', 'active');
