INSERT INTO public.education_major (id, name, status) VALUES (0, 'Unknown', 'inactive');
INSERT INTO public.education_major (id, name, status) VALUES (8713, 'Accounting', 'active');
INSERT INTO public.education_major (id, name, status) VALUES (8714, 'Administrative Development', 'active');
INSERT INTO public.education_major (id, name, status) VALUES (8715, 'Agriculture', 'active');
INSERT INTO public.education_major (id, name, status) VALUES (8716, 'Applied Technology', 'active');
INSERT INTO public.education_major (id, name, status) VALUES (8717, 'Archeology', 'active');
INSERT INTO public.education_major (id, name, status) VALUES (8718, 'Architecture', 'active');
INSERT INTO public.education_major (id, name, status) VALUES (8719, 'Astronomy', 'active');
INSERT INTO public.education_major (id, name, status) VALUES (8720, 'Astrophysics', 'active');
INSERT INTO public.education_major (id, name, status) VALUES (8721, 'Artificial Intelligence', 'active');
INSERT INTO public.education_major (id, name, status) VALUES (8722, 'Biology', 'active');
INSERT INTO public.education_major (id, name, status) VALUES (8723, 'Biochemistry', 'active');
INSERT INTO public.education_major (id, name, status) VALUES (8724, 'Biomaterials', 'active');
INSERT INTO public.education_major (id, name, status) VALUES (8725, 'Biomedical Science', 'active');
INSERT INTO public.education_major (id, name, status) VALUES (8726, 'Business Administration', 'active');
INSERT INTO public.education_major (id, name, status) VALUES (8727, 'Chemistry', 'active');
INSERT INTO public.education_major (id, name, status) VALUES (8728, 'Child Study and Human Development', 'active');
INSERT INTO public.education_major (id, name, status) VALUES (8729, 'Cognitive and Brain Sciences', 'active');
INSERT INTO public.education_major (id, name, status) VALUES (8730, 'Communications and Media', 'active');
INSERT INTO public.education_major (id, name, status) VALUES (8731, 'Computer Science', 'active');
INSERT INTO public.education_major (id, name, status) VALUES (8732, 'Criminology/Criminal Justice', 'active');
INSERT INTO public.education_major (id, name, status) VALUES (8733, 'Dentistry', 'active');
INSERT INTO public.education_major (id, name, status) VALUES (8734, 'Design', 'active');
INSERT INTO public.education_major (id, name, status) VALUES (8735, 'Ecology', 'active');
INSERT INTO public.education_major (id, name, status) VALUES (8736, 'Education', 'active');
INSERT INTO public.education_major (id, name, status) VALUES (8737, 'Engineering', 'active');
INSERT INTO public.education_major (id, name, status) VALUES (8738, 'Environmental Studies', 'active');
INSERT INTO public.education_major (id, name, status) VALUES (8739, 'Environmental Technology', 'active');
INSERT INTO public.education_major (id, name, status) VALUES (8740, 'Epidemiology', 'active');
INSERT INTO public.education_major (id, name, status) VALUES (8741, 'Finance/Banking/Economics', 'active');
INSERT INTO public.education_major (id, name, status) VALUES (8742, 'Fine Arts', 'active');
INSERT INTO public.education_major (id, name, status) VALUES (8743, 'Food Science', 'active');
INSERT INTO public.education_major (id, name, status) VALUES (8744, 'Forest Studies', 'active');
INSERT INTO public.education_major (id, name, status) VALUES (8745, 'Geology', 'active');
INSERT INTO public.education_major (id, name, status) VALUES (8746, 'Global Health/Healthcare', 'active');
INSERT INTO public.education_major (id, name, status) VALUES (8747, 'Hospice/Palliative Care', 'active');
INSERT INTO public.education_major (id, name, status) VALUES (8748, 'Human Resource Management', 'active');
INSERT INTO public.education_major (id, name, status) VALUES (8749, 'Information Technology', 'active');
INSERT INTO public.education_major (id, name, status) VALUES (8750, 'International Relations', 'active');
INSERT INTO public.education_major (id, name, status) VALUES (8751, 'Journalism', 'active');
INSERT INTO public.education_major (id, name, status) VALUES (8752, 'Islamic Law', 'active');
INSERT INTO public.education_major (id, name, status) VALUES (8753, 'Language (ex. French, Spanish, Russian, etc.)', 'active');
INSERT INTO public.education_major (id, name, status) VALUES (8754, 'Laser Research and Applications', 'active');
INSERT INTO public.education_major (id, name, status) VALUES (8755, 'Marketing', 'active');
INSERT INTO public.education_major (id, name, status) VALUES (8756, 'Mathematics', 'active');
INSERT INTO public.education_major (id, name, status) VALUES (8757, 'Medicine', 'active');
INSERT INTO public.education_major (id, name, status) VALUES (8759, 'Nutrition', 'active');
INSERT INTO public.education_major (id, name, status) VALUES (8760, 'Optometry', 'active');
INSERT INTO public.education_major (id, name, status) VALUES (8761, 'Physics', 'active');
INSERT INTO public.education_major (id, name, status) VALUES (8762, 'Pharmacy', 'active');
INSERT INTO public.education_major (id, name, status) VALUES (8763, 'Political Studies and Public Policy', 'active');
INSERT INTO public.education_major (id, name, status) VALUES (8764, 'Psychology', 'active');
INSERT INTO public.education_major (id, name, status) VALUES (8765, 'Social Sciences', 'active');
INSERT INTO public.education_major (id, name, status) VALUES (8766, 'Social Work', 'active');
INSERT INTO public.education_major (id, name, status) VALUES (8767, 'Statistics', 'active');
INSERT INTO public.education_major (id, name, status) VALUES (8768, 'Translation', 'active');
INSERT INTO public.education_major (id, name, status) VALUES (8769, 'Urban Planning and Policy', 'active');
INSERT INTO public.education_major (id, name, status) VALUES (8770, 'Veterinary', 'active');
INSERT INTO public.education_major (id, name, status) VALUES (8778, 'Law', 'active');
