INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (0, NULL, 'Unknown', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8577, '2411', 'Accountant', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8484, '3343', 'Administrative assistant', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8485, '622', 'Agricultural, fishery or related laborer', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8580, '2132', 'Agronomist or related', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8581, '5164', 'Aircraft pilot or related professional', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8582, '2632', 'Anthropologist', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (10000, '2632', 'Archaeologist', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8584, '2161', 'Architect or planner', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8585, '262', 'Archivist, curator, or librarian', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8586, '0', 'Armed forces/military', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8488, '8212', 'Assembler (electrical equipment)', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8489, '8211', 'Assembler (mechanical-machinery)', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8589, '9321', 'Assembling labourer', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8590, '5161', 'Astrologer or related worker', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8591, '3421', 'Athlete or sportsperson', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8492, '7512', 'Baker or pastry-cook', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8493, '722', 'Blacksmith, tool maker, or forge worker', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8496, '7111', 'Builder (traditional materials)', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8498, '9313', 'Building construction labourer', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8499, '24', 'Business professional not elsewhere classified', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8502, '2651', 'Cartoonist', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (10001, '3434', 'Chef', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8504, '5162', 'Companion or valet', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8505, '2514', 'Computer programmer', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8507, '931', 'Construction labourer (roads, dams)', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8511, '754', 'Craftsman (wood, textile, leather)', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8512, '4132', 'Data entry operator', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8516, '7411', 'Electrician', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8517, '3333', 'Employment agent or labour contractor', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8519, '5241', 'Fashion or other model', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8521, '1211', 'Finance professional', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8522, '5411', 'Fire-fighter', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8524, '7122', 'Floor layer or tile setter', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8525, '7515', 'Food & beverage taster or grader', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8527, '9611', 'Garbage collector', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8529, '1219', 'General manager in wholesale or retail', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8528, '1120', 'General manager (own or small business)', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8530, '514', 'Hairdresser, barber, beautician or related', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8531, '5322', 'Healthcare professional (hospice)', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8533, '5151', 'Housekeeper ', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8535, '351', 'Information technology professional', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8537, '6121', 'Livestock Worker', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8538, '816', 'Machine Operator (baked-goods, cereal & chocolate-products)', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8543, '7412', 'Mechanic (electrical)', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8486, '3339', 'Auctioneer', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8495, '711', 'Bricklayer', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8500, '7511', 'Butcher', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8497, '3112', 'Inspector, building', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8618, '2261', 'Medical and Dental Prosthetic Technicians', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8603, '2165', 'Surveyor, land', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (10002, '3315', 'Appraiser', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (10003, '3251', 'Dental Assistants and Therapists', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (10004, '7113', 'Stonemason', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (10005, '7511', 'Fishmonger', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (10006, '2165', 'Cartographer', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (10007, '2131', 'Botanist', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (10008, '2212', 'Pathologist', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (10010, '2267', 'Optician, ophthalmic', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (10011, '7312', 'Tuner, musical instrument', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (10012, '2114', 'Geophysicist', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (10013, '2144', 'Engineer, diesel', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (10014, '7231', 'Mechanic, diesel: motor vehicle', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (10015, '7233', 'Mechanic, engine: diesel (except motor vehicle)', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (10016, '2529', 'Scientist, data mining', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (10017, '235', 'Other Teaching Professionals', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (10018, '325', 'Other Health Associate Professionals', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (10019, '516', 'Other Personal Services Workers', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8703, NULL, 'Student', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8595, '3313', 'Bookkeeper', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8602, '7115', 'Carpenter or joiner', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8606, '2113', 'Chemist', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8607, '5311', 'Child-care worker', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8610, '7114', 'Concrete placer, finisher or related', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8612, '5120', 'Cook', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8613, '1219', 'Corporate director or chief executive', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8614, '754', 'Craft and related trades worker (pottery, hand metal work, glass maker, painter, jewelry etc.)', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8617, '3432', 'Decorator and commercial designer', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8619, '2261', 'Dentist', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8620, '2265', 'Dietician & nutritionist', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8621, '3118', 'Draughtsperson', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8622, '83', 'Driver and mobile-plant operator', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8623, '2631', 'Economist', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8624, '2351', 'Education methods specialist', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8632, '2654', 'Filmmaker', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8593, '213', 'Biologist', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (9426, NULL, 'Bachelor''s Degree', 'inactive');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8678, '2131', 'Pharmacologist', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8705, '23', 'Teacher', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8699, '2632', 'Sociologist', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (10020, '524', 'Other Sales Workers', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (10021, '818', 'Other Stationary Plant and Machine Operators', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (10022, '2131', 'Zoologist', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (9441, '1219', 'Business Owner', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8780, '2149', 'Engineer (biomedical) ', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8605, '2145', 'Engineer (chemical)', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8627, '2142', 'Engineer (civil)', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8628, '2151', 'Engineer (electrical)', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8781, '2152', 'Engineer (electronic) ', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8782, '2141', 'Engineer (industrial) ', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8629, '2144', 'Engineer (mechanical)', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8785, '214', 'Engineer (other)', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8783, '2145', 'Engineer (petroleum)', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8630, '611', 'Farmer (crop and vegetable)', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8635, '622', 'Fishery, hunting or trapping labourer', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8638, '621', 'Forestry worker and logger', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (9443, '9622', 'Freelance', 'inactive');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8643, '2166', 'Graphic designer', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8646, '2211', 'Healthcare professional (medical doctor)', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8647, '3222', 'Healthcare professional (midwife)', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8648, '222', 'Healthcare professional (nurse)', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8650, '226', 'Healthcare professional (other)', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8651, '2264', 'Healthcare professional (physical therapist)', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (9436, '5152', 'Housewife', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8653, '1114', 'Humanitarian worker', 'inactive');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8786, '1212', 'Human resource manager', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8655, '3321', 'Insurance', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8656, '2612', 'Judge', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8657, '2611', 'Lawyer', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8539, '811', 'Machine Operator (cement/other minerals)', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8661, '815', 'Machine Operator (fur & leather)', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8662, '816', 'Machine Operator (meat and fish)', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8663, '9329', 'Manufacturing labourer', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8664, '2431', 'Marketing professional', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8665, '2120', 'Mathematician or related professional', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8544, '723', 'Mechanic (machinery)', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8545, '7213', 'Metal worker', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8669, '2112', 'Meteorologist', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8546, '811', 'Mining and quarrying worker', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8670, '811', 'Mining or quarry worker', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8547, '83', 'Motor vehicle driver (cab, truck, or other)', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8758, '222', 'Nursing', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8673, '261', 'Other legal professional', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8674, '265', 'Performing artist (musician, actor/actreess, etc.)', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8675, '5414', 'Personal and Protective Service Worker', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8552, '3213', 'Pharmaceutical assistant', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8677, '2262', 'Pharmacist', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8679, '3431', 'Photographer', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8680, '352', 'Photographer, image or sound equipment operator', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8681, '712', 'Plasterer/painter/varnisher', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8556, '7126', 'Plumber or pipe fitter', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8683, '5412', 'Police officer', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8684, '6122', 'Poultry producer', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8685, '231', 'Professor or Lecturer', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8686, '2634', 'Psychologist', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8687, '3413', 'Religious professional', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8688, '3119', 'Robotic Specialist', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8689, '3257', 'Safety, health & quality inspector', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8690, '332', 'Sales professional', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8691, '3322', 'Sales representatives/merchant/trader', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8692, '2351', 'School inspector', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8693, '441', 'Scribe or related worker', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8694, '4120', 'Secretary', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8565, '753', 'Sewer, embroiderer or related', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8696, '315', 'Ship and aircraft controller or technician', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8697, '2632', 'Social scientist', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8567, '2635', 'Social work professional', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8784, '2512', 'Software engineer', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8700, '2352', 'Special education teacher', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8701, '2120', 'Statistician', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8702, '5212', 'Street food vendor', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8571, '753', 'Tailor, dressmaker or hatter', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8706, '421', 'Teller or other counter clerk', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8707, '7534', 'Upholsterer or related worker', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8708, '2250', 'Veterinarian', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8574, '513', 'Waiter, waitress, bartender, restaurant worker', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8710, '721', 'Welder or flamecutter', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8711, '752', 'Woodworker', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8712, '2641', 'Writer', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8649, '2267', 'Optometrist', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8672, '754', 'Other Craft and Related Workers', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (8642, '2114', 'Geologist', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (10023, '3112', 'Inspector, fire', 'active');
INSERT INTO public.occupation (id, isco08_code, name, status) VALUES (10037, '2266', 'Audiologist and Speech Therapists', 'active');
